
# Language/versions
language: node_js
node_js:
  - "0.12"

# Build only master (and pull-requests)
branches:
  only:
    - master

# Build script
script: make ci

# Deploy settings
deploy:
  provider: heroku
  api_key:
    secure: XGfwWPbvvcqGaVJKiGq61nvQtNjylexukcQHqzVRUgrsclQHnN7DbveP9YycfhSG7zgGChDRMmZYmJwvofjfhpFyODMJJtayGHDy6EBW08mViiqzH16XF8qV8vz6MVQRakTZcgdyv51To1cYY3LnuFx5wgEX808zPU1wXb2tY70=
  app: fedbot

# Send notifications to the FEDs slack channel
notifications:
  slack: thefeds:vG3hLYB07EwTYpQFp3TNUx82
